In [1]:
# Initial Imports
import requests
import pandas as pd
import json
import numpy as np
#import pymongo
from path import Path
from datetime import datetime
from datetime import timedelta
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
# Import API Key
from config import key
import config
# Documentation:
#https://www.worldweatheronline.com/developer/my/analytics.aspx?key_id=222419

In [3]:
# set string variables
#DEFAULT_DATABASE = 'wind_solar_data' 
#USERNAME = config.USERNAME
#PASSWORD = config.PASSWORD

#create connection to database
#client = pymongo.MongoClient(f"mongodb+srv://{USERNAME}:{PASSWORD}@austin-green-energy.pwzpm.mongodb.net/{DEFAULT_DATABASE}?retryWrites=true&w=majority")
#try:
#    client.server_info()
#    print("Mongodb connected")
#except:
#    print("The Mongodb failed to connect. Check username/password in connection string.")

In [4]:
# select database
#db = client.get_database('wind_solar_data')
# select collection
#collection = db.wind_data

# pull collection into dataframe
#wind_df = pd.DataFrame(list(collection.find()))
#wind_df

In [5]:
# Import API Key
#from config import key

# Documentation:
#https://www.worldweatheronline.com/developer/my/analytics.aspx?key_id=222419

In [6]:
# Make a request to the worldweatheronline local history weather API page
def makeARequest(location, startDate, endDate, yourAPIKey):
    baseURL = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx"
    timeInterval = "1"
    outputFormatToReturn = "json"

    requestURL = f"{baseURL}?q={location}&date={startDate}&enddate={endDate}&tp={timeInterval}&format={outputFormatToReturn}&key={yourAPIKey}"
    
    response = requests.get(requestURL)

    if response.status_code == 200:
        responseJson = response.json()
        return responseJson
    else:
        return print(response.status_code)

In [7]:
# Pull the wind variables from the responseJson 
def monthlyHistoricalWeather(firstDayOfMonth, lastDayOfMonth, jsonResponse):
    
    first = datetime.strptime(firstDayOfMonth, '%Y-%m-%d')
    last = datetime.strptime(lastDayOfMonth, '%Y-%m-%d')
    numberOfDays = last.day - first.day

    HourlyHistoricalWeather = []
    
    for day in np.arange(0,numberOfDays + 1,1):
        for hour in np.arange(0,24,1):
            HourlyHistoricalWeather.append({
                "Date" : jsonResponse["data"]["weather"][day]["date"],
                "Time" : jsonResponse["data"]["weather"][day]["hourly"][hour]["time"],
                "WindSpeed_mph" : jsonResponse["data"]["weather"][day]["hourly"][hour]["windspeedMiles"],
                "WindDirection_degrees" : jsonResponse["data"]["weather"][day]["hourly"][hour]["winddirDegree"],
                "WindGust_mph" : jsonResponse["data"]["weather"][day]["hourly"][hour]["WindGustMiles"],
                "Humidity_percent" : jsonResponse["data"]["weather"][day]["hourly"][hour]["humidity"],
                "Temp_F" : jsonResponse["data"]["weather"][day]["hourly"][hour]["tempF"]
            })

    return HourlyHistoricalWeather

In [8]:

# Store the variables in a DataFrame
def monthlyHistoricalWeatherDF(month):
    weatherDataFrame = pd.DataFrame(month)
    return weatherDataFrame

In [9]:
# Define the Latitude and longitude of Hackberry Wind Farm
    # https://www.thewindpower.net/windfarm_en_4012_hackberry.php
    # Latitude: 32.776111
    # Longitude: -99.476444
latLong = "32.776111,-99.476444"

In [10]:
# January
date = "2019-01-01"
enddate = "2019-01-31"

responseJson = makeARequest(latLong, date, enddate, key)

January = monthlyHistoricalWeather(date, enddate, responseJson)
JanuaryDF = monthlyHistoricalWeatherDF(January)
JanuaryDF.head()

Date Time WindSpeed_mph WindDirection_degrees WindGust_mph  \
0  2019-01-01    0            12                   126           24   
1  2019-01-01  100            13                    89           23   
2  2019-01-01  200            14                    53           23   
3  2019-01-01  300            15                    17           22   
4  2019-01-01  400            14                    18           21   

  Humidity_percent Temp_F  
0               73     35  
1               74     33  
2               76     32  
3               77     30  
4               77     29

In [11]:
# February
date = "2019-02-01"
enddate = "2019-02-28"

responseJson = makeARequest(latLong, date, enddate, key)

February = monthlyHistoricalWeather(date, enddate, responseJson)
FebruaryDF = monthlyHistoricalWeatherDF(February)

In [12]:

# March
date = "2019-03-01"
enddate = "2019-03-31"

responseJson = makeARequest(latLong, date, enddate, key)

March = monthlyHistoricalWeather(date, enddate, responseJson)
MarchDF = monthlyHistoricalWeatherDF(March)

In [13]:
# April
date = "2019-04-01"
enddate = "2019-04-30"

responseJson = makeARequest(latLong, date, enddate, key)

April = monthlyHistoricalWeather(date, enddate, responseJson)
AprilDF = monthlyHistoricalWeatherDF(April)

In [14]:

# May
date = "2019-05-01"
enddate = "2019-05-31"

responseJson = makeARequest(latLong, date, enddate, key)

May = monthlyHistoricalWeather(date, enddate, responseJson)
MayDF = monthlyHistoricalWeatherDF(May)

In [15]:
# June
date = "2019-06-01"
enddate = "2019-06-30"

responseJson = makeARequest(latLong, date, enddate, key)

June = monthlyHistoricalWeather(date, enddate, responseJson)
JuneDF = monthlyHistoricalWeatherDF(June)

In [16]:

# July
date = "2019-07-01"
enddate = "2019-07-31"

responseJson = makeARequest(latLong, date, enddate, key)

July = monthlyHistoricalWeather(date, enddate, responseJson)
JulyDF = monthlyHistoricalWeatherDF(July)

In [17]:
# August
date = "2019-08-01"
enddate = "2019-08-31"

responseJson = makeARequest(latLong, date, enddate, key)

August = monthlyHistoricalWeather(date, enddate, responseJson)
AugustDF = monthlyHistoricalWeatherDF(August)

In [18]:
# September
date = "2019-09-01"
enddate = "2019-09-30"

responseJson = makeARequest(latLong, date, enddate, key)

September = monthlyHistoricalWeather(date, enddate, responseJson)
SeptemberDF = monthlyHistoricalWeatherDF(September)

In [19]:
# October
date = "2019-10-01"
enddate = "2019-10-31"

responseJson = makeARequest(latLong, date, enddate, key)

October = monthlyHistoricalWeather(date, enddate, responseJson)
OctoberDF = monthlyHistoricalWeatherDF(October)

In [20]:
# November
date = "2019-11-01"
enddate = "2019-11-30"

responseJson = makeARequest(latLong, date, enddate, key)

November = monthlyHistoricalWeather(date, enddate, responseJson)
NovemberDF = monthlyHistoricalWeatherDF(November)

In [21]:
# December
date = "2019-12-01"
enddate = "2019-12-31"

responseJson = makeARequest(latLong, date, enddate, key)

December = monthlyHistoricalWeather(date, enddate, responseJson)
DecemberDF = monthlyHistoricalWeatherDF(December)

In [22]:
# Combine each month into a single DataFrame
hourlyWeatherDF2019 = JanuaryDF.append([FebruaryDF, MarchDF, AprilDF, MayDF, JuneDF, JulyDF, AugustDF, SeptemberDF, OctoberDF, NovemberDF, DecemberDF]) 
index = np.arange(0,24*365,1)
hourlyWeatherDF2019 = hourlyWeatherDF2019.set_index(index)
hourlyWeatherDF2019

Date  Time WindSpeed_mph WindDirection_degrees WindGust_mph  \
0     2019-01-01     0            12                   126           24   
1     2019-01-01   100            13                    89           23   
2     2019-01-01   200            14                    53           23   
3     2019-01-01   300            15                    17           22   
4     2019-01-01   400            14                    18           21   
...          ...   ...           ...                   ...          ...   
8755  2019-12-31  1900             6                   175           12   
8756  2019-12-31  2000             6                   176           13   
8757  2019-12-31  2100             7                   176           14   
8758  2019-12-31  2200             7                   176           15   
8759  2019-12-31  2300             7                   175           16   

     Humidity_percent Temp_F  
0                  73     35  
1                  74     33  
2                  76     32  
3                  77     30  
4                  77     29  
...               ...    ...  
8755               39     49  
8756               42     47  
8757               45     46  
8758               46     46  
8759               48     45  

[8760 rows x 7 columns]

In [23]:
hourlyWeatherDF2019.dtypes

Date                     object
Time                     object
WindSpeed_mph            object
WindDirection_degrees    object
WindGust_mph             object
Humidity_percent         object
Temp_F                   object
dtype: object

In [24]:
hourlyWeatherDF2019.to_csv(r'Output/hourlyWeatherDF2019.csv', index = False)

# Performing ETL on Wind Data at Hackberry Wind Farm

In [25]:
# def cleaningDataFrame_datetime(df):
#     df['Date'] = pd.to_datetime(df['Date'])
#     df['Time'] = df['Time'].astype(int)
#     df['Time'] = (df['Time']/100).astype(int)
#     df['Time'] = df['Time'].astype('timedelta64[h]')
#     df['Time'] = df['Time'] - pd.to_timedelta(df['Time'].dt.days, unit='d')
#     df['Date_Time'] = df['Date'] + df['Time']
#     df = df.drop(['Time', 'Date'], 1)
#     return df

In [26]:
hourlyWeatherDF2019['Date'] = pd.to_datetime(hourlyWeatherDF2019['Date'] )

In [27]:
hourlyWeatherDF2019.dtypes

In [28]:
hourlyWeatherDF2019['Time'] = hourlyWeatherDF2019['Time'].astype(int)

In [29]:
hourlyWeatherDF2019['Time'] = hourlyWeatherDF2019['Time']/100

In [30]:
hourlyWeatherDF2019['Time'] = hourlyWeatherDF2019['Time'].astype(int)

In [31]:
hourlyWeatherDF2019['time'] =pd.to_timedelta(hourlyWeatherDF2019['Time'], unit='h')

In [33]:
# Creating new column called 'hour' in timedelta format without date
hourlyWeatherDF2019['Time'] = hourlyWeatherDF2019['Time'] - pd.to_timedelta(hourlyWeatherDF2019['Time'].dt.days, unit='d')

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
#hourlyWeatherDF2019.dtypes

In [ ]:
# Combining Date and hour to a single column as they are in datetime and timedelta formats
#hourlyWeatherDF2019['time_combined'] = hourlyWeatherDF2019['Date'] + hourlyWeatherDF2019['time']

In [ ]:
# Dropping the original 'Time' column from 
#hourlyWeatherDF2019 = hourlyWeatherDF2019.drop(['Time', 'Date', 'time'], 1)

In [ ]:
# Renaming time column name.
hourlyWeatherDF2019.rename(columns = {'time_combined':'time'}, inplace = True)

In [ ]:
# Re-arranging the column headers
hourlyWeatherDF2019 = hourlyWeatherDF2019[['time', 'WindSpeed_mph', 'WindDirection_degrees', 'WindGust_mph', 'Temp_F', 'Humidity_percent']]

In [ ]:
hourlyWeatherDF2019['WindSpeed_mph'] = hourlyWeatherDF2019['WindSpeed_mph'].astype(int)

In [ ]:
hourlyWeatherDF2019['WindDirection_degrees'] = hourlyWeatherDF2019['WindDirection_degrees'].astype(int)

In [ ]:
hourlyWeatherDF2019['WindGust_mph'] = hourlyWeatherDF2019['WindGust_mph'].astype(int)

In [ ]:
hourlyWeatherDF2019['Humidity_percent'] = hourlyWeatherDF2019['Humidity_percent'].astype(int)

In [ ]:
hourlyWeatherDF2019['Temp_F'] = hourlyWeatherDF2019['Temp_F'].astype(int)

In [ ]:
weather2019Clean = hourlyWeatherDF2019.drop(hourlyWeatherDF2019.index[0])

In [ ]:
weather2019Clean.to_csv(r'Output/weather_wind.csv', index = False)

In [ ]:
weather2019Clean.copy()

# Importing and Performing ETL on Hackberry Wind Energy Data

In [ ]:
data = "Resources/Hackberry_Generation.csv"
Hackberry_df = pd.read_csv(data)
Hackberry_df

In [ ]:
Hackberry_df.dtypes

In [ ]:
# Dropping Unit Column
Hackberry_df = Hackberry_df.drop('Unit', 1)

In [ ]:
# Renaming column name from 'Hour Ending' to 'Hour'
Hackberry_df.rename(columns = {'Hour Ending':'Hour'}, inplace = True)

In [ ]:
# Converting Date to datetime
Hackberry_df['Date'] = pd.to_datetime(Hackberry_df['Date'], format='%Y%m%d')

In [ ]:
# Checking data type
Hackberry_df.dtypes

In [ ]:
# Removing the last two characters from the hour column as the times are hourly
Hackberry_df['Hour'] = Hackberry_df['Hour'].astype(str).str[:-2].astype(np.int64)

In [ ]:
# Checking Hour data type
Hackberry_df.dtypes

In [ ]:
Hackberry_df['hour'] =pd.to_timedelta(Hackberry_df['Hour'], unit='h')

In [ ]:
# Creating new column called 'hour' in timedelta format without date
Hackberry_df['hour'] = Hackberry_df['hour'] - pd.to_timedelta(Hackberry_df['hour'].dt.days, unit='d')

In [ ]:
# Dropping the original 'Hour' column
Hackberry_df = Hackberry_df.drop('Hour', 1)

In [ ]:
# Re-arranging the column headers
Hackberry_df = Hackberry_df[["Date", "hour", "MWH"]]

In [ ]:
Hackberry_df.dtypes

In [ ]:
# Combining Date and hour to a single column as they are in datetime and timedelta formats
Hackberry_df['time'] = Hackberry_df['Date'] + Hackberry_df['hour']

In [ ]:
# Re-arranging the column headers and removing the Date and hour columns
Hackberry_df = Hackberry_df[["time", "MWH"]]

In [ ]:
Hackberry_df.dtypes

In [ ]:
Hackberry_df.copy()

In [ ]:
# Removing rows to include only 2019 year data to include same time range as wind data
Hackberry2019 = Hackberry_df.drop(Hackberry_df.index[8759:13871])

In [ ]:
Hackberry2019.to_csv(r'Output/Hackberry_MHW.csv', index = False)

## Merging Hackberry Energy Data with Wind Data

In [ ]:
hackberryWindMWH = pd.merge(weather2019Clean, Hackberry2019, on='time', how='outer')

In [ ]:
hackberryWindMWH =hackberryWindMWH.drop(hackberryWindMWH.index[8760])

In [ ]:
hackberryWindMWH.dtypes

In [ ]:
hackberryWindMWH.to_csv(r'Output/Hackberry_Wind_MHW.csv', index = False)

In [ ]:
hackberryWindMWH.copy()

In [ ]:
# There are 72 turbines in Hackberry Farm.
hackberryWindMWH['MWH'] = hackberryWindMWH['MWH']/72

In [ ]:
hackberryWindMWH.dtypes

In [ ]:
hackberry = hackberryWindMWH.dropna()

In [ ]:
#hackberry["WindSpeed_mph"] = hackberry["WindSpeed_mph"].round(0).astype(int)

## Linear Regression

In [34]:
import warnings
warnings.filterwarnings('ignore')

In [35]:
from pathlib import Path
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [36]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [37]:
# Visually inspect the data
plt.scatter(hackberry.WindSpeed_mph, hackberry.MWH)
plt.xlabel('Wind Speed')
plt.ylabel('MHW')
plt.show()

NameError: name 'hackberry' is not defined

##  It can be concluded that linear regression on wind speed alone does not track the power generated

In [38]:
# Save csv file to be used later without going through the ETL process.
hackberry.to_csv(r'Output/hackberry_encoded.csv', index = False)
hackberry.to_csv(r'Resources/hackberry_encoded.csv', index = False)

NameError: name 'hackberry' is not defined

In [39]:
# Load the csv file from resources
data = "Resources/hackberry_encoded.csv"
hackberry_encoded = pd.read_csv(data)

In [40]:
hackberryEncoded = hackberry_encoded.drop(["time"], axis=1)

In [41]:
hackberryEncoded["WindSpeed_mph"] = hackberryEncoded["WindSpeed_mph"].round(0).astype(int)

In [42]:
hackberryEncoded["WindDirection_degrees"] = hackberryEncoded["WindDirection_degrees"].round(0).astype(int)

In [43]:
hackberryEncoded["Temp_F"] = hackberryEncoded["Temp_F"].round(0).astype(int)

In [44]:
hackberryEncoded["Humidity_percent"] = hackberryEncoded["Humidity_percent"].round(0).astype(int)

In [45]:
hackberryEncoded["WindGust_mph"] = hackberryEncoded["WindGust_mph"].round(0).astype(int)

In [46]:
hackberryEncoded["MWH"] = hackberryEncoded["MWH"].round(0).astype(int)

In [47]:
# Creating the scaler instance
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [48]:
hackberry_scaled = data_scaler.fit_transform(hackberryEncoded)

In [49]:
hackberry_scaled[:5]

array([[ 0.3608004 , -1.05022902,  0.74188853, -1.84416382,  0.9587771 ,
         1.76060903],
       [ 0.56803347, -1.53116107,  0.74188853, -1.89917018,  1.06779963,
         0.40636576],
       [ 0.77526654, -2.01209313,  0.60454765, -2.00918289,  1.1223109 ,
         0.40636576],
       [ 0.56803347, -1.99873391,  0.46720677, -2.06418925,  1.1223109 ,
         0.40636576],
       [ 0.56803347, -1.98537468,  0.32986589, -2.11919561,  1.06779963,
         0.40636576]])

In [50]:
print(np.mean(hackberry_scaled[:,0]))
print(np.std(hackberry_scaled[:,0]))

-1.1196037626729142e-16
1.0


In [51]:
# Define the features set.
X = hackberryEncoded.copy()
X = X.drop("MWH", axis=1)
X.head()

WindSpeed_mph  WindDirection_degrees  WindGust_mph  Temp_F  \
0             13                     89            23      33   
1             14                     53            23      32   
2             15                     17            22      30   
3             14                     18            21      29   
4             14                     19            20      28   

   Humidity_percent  
0                74  
1                76  
2                77  
3                77  
4                76

In [52]:
# Define the target set.
y = hackberryEncoded["MWH"].ravel()
y[:5]

array([2, 1, 1, 1, 1])

# Multiple Linear Regression Model

In [53]:
from sklearn import linear_model
#from sklearn.metrics import mean_squared_error

In [54]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=9)

In [55]:
# with sklearn
lm = linear_model.LinearRegression()
model = lm.fit(X,y)

In [56]:
predictions = lm.predict(X)

In [57]:
#Return the coefficient of determination R^2 of the prediction
#The coefficient R^2 is defined as (1 - u/v), where u is the residual sum of squares ((y_true - y_pred) ** 2).sum() and 
#v is the total sum of squares ((y_true - y_true.mean()) ** 2).sum().
#The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse).
#A constant model that always predicts the expected value of y,
#disregarding the input features, would get a R^2 score of 0.0.

lm.score(X,y)

0.3423667651596264

In [58]:
lm.coef_

array([-8.95710852e-03,  5.44010624e-04,  6.16989085e-02,  5.67109374e-05,
        2.84278391e-03])

In [59]:
lm.intercept_

-0.5403324965151426

# Using Balanced Random Forest Classifier

In [60]:
# Resample the training data with the RandomOversampler
from imblearn.ensemble import BalancedRandomForestClassifier
brfc = BalancedRandomForestClassifier(n_estimators=100, random_state=1)
#split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)
brfc.fit(X_train, y_train)
Counter(y_train)

Counter({0: 3089, 1: 2421, 2: 1058})

In [61]:
# Calculated the balanced accuracy score
y_pred = brfc.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7292707753306864

In [62]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[764, 156,  87],
       [112, 475, 186],
       [ 10,  66, 334]], dtype=int64)

In [63]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.86      0.76      0.90      0.81      0.82      0.67      1007
          1       0.68      0.61      0.84      0.65      0.72      0.51       773
          2       0.55      0.81      0.85      0.66      0.83      0.69       410

avg / total       0.74      0.72      0.87      0.72      0.79      0.62      2190



In [64]:
# List the features sorted in descending order by feature importance
importances = brfc.feature_importances_
sorted(zip(brfc.feature_importances_, X.columns), reverse=True)

[(0.3001313240231106, 'WindGust_mph'),
 (0.2164485679681333, 'WindDirection_degrees'),
 (0.17125360268903886, 'Temp_F'),
 (0.17047127842672988, 'Humidity_percent'),
 (0.1416952268929874, 'WindSpeed_mph')]

# Random Forest Classifier

In [65]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [66]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [67]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

In [68]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [69]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [70]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [71]:
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.7488584474885844


In [72]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.14092194, 0.2281864 , 0.27265895, 0.17730254, 0.18093017])

In [73]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.2726589497161064, 'WindGust_mph'),
 (0.22818639974566826, 'WindDirection_degrees'),
 (0.1809301724870095, 'Humidity_percent'),
 (0.17730254227777692, 'Temp_F'),
 (0.140921935773439, 'WindSpeed_mph')]

In [74]:
print("Classification Report")
print(classification_report(y_test, predictions))

Classification Report
              precision    recall  f1-score   support

           0       0.82      0.83      0.83      1007
           1       0.67      0.70      0.68       773
           2       0.71      0.63      0.67       410

    accuracy                           0.75      2190
   macro avg       0.74      0.72      0.73      2190
weighted avg       0.75      0.75      0.75      2190



# AdaBoostClassifier

In [75]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [76]:
train_X, test_X, train_y, test_y = train_test_split(X, y, random_state=1)

In [77]:
#Forest to be composed of trees with a single decision node and two leaves. 400 estimators to specify the total number of trees in forest
classifier = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=400)
classifier.fit(train_X, train_y)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=400)

In [78]:
predictions = classifier.predict(test_X)

In [79]:
confusion_matrix(test_y, predictions)

array([[749, 204,  52],
       [200, 525,  99],
       [ 32, 126, 203]], dtype=int64)

In [80]:
classifier.score(X, y)

0.6764101393012103

# Neural Network

In [83]:
import tensorflow as tf
# Define the model - deep neural net
number_input_features = 3
hidden_nodes_layer1 =  number_input_features*3
hidden_nodes_layer2 =  number_input_features*3

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="linear")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="linear"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="linear"))

# Compile the Sequential model together and customize metrics
nn.compile(optimizer="sgd", loss=tf.keras.losses.MeanSquaredError(), metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
# Example from https://machinelearningmastery.com/regression-tutorial-keras-deep-learning-library-python/
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_val_score, KFold
from keras.models import Sequential
from sklearn.metrics import accuracy_score
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.metrics import r2_score
seed = 1

def baseline_model():
    model = Sequential()
    model.add(Dense(10, input_dim=3, activation='linear'))
    model.add(Dense(1))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model


# estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=100, batch_size=100, verbose=False)
# kfold = KFold(n_splits=10, random_state=seed)
# results = cross_val_score(estimator, X, y, cv=kfold)
# print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

# estimator.fit(X, y)
# prediction = estimator.predict(X)
# accuracy_score(y, prediction)

estimator = KerasRegressor(build_fn=baseline_model)
estimator.fit(X_train_scaled, y_train, nb_epoch=100, batch_size=100, verbose=False, shuffle=False)
prediction = estimator.predict(X_test_scaled)
r2_score(y_test, prediction)

# model = baseline_model()
# model.fit(X, y, nb_epoch=100, batch_size=100, verbose=False, shuffle=False)
# prediction = model.predict(X)

In [ ]:
# https://nbviewer.jupyter.org/github/srnghn/ml_example_notebooks/blob/master/Predicting%20Wine%20Types%20with%20Neural%20Networks.ipynb
from sklearn.neural_network import MLPClassifier

model = MLPClassifier()
model.fit(X_train_scaled, y_train)
accuracy_score(y_train, model.predict(X_train_scaled))